name: edusys_client
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.1
  provider: ^6.1.2
  data_table_2: ^2.5.16
  dio: ^5.7.0
  brasil_fields: ^1.15.0
  window_manager: ^0.4.3
  advanced_datatable: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
